namespace OuterloopLabApi.Models;

public sealed record ConvertRequest(
    string FromCurrency,
    string ToCurrency,
    decimal Amount
);

public sealed record ConversionPreview(
    string AuditId,
    string FromCurrency,
    string ToCurrency,
    decimal InputAmount,
    decimal Rate,
    decimal ConvertedAmount,
    DateTimeOffset BackendExecutionTimestampUtc,
    string? ProviderDate
);

public sealed class ConversionAudit
{
    // Cosmos item id
    public string auditId { get; set; } = default!;
    // Partition key
    public string tenantId { get; set; } = "default";

    public string fromCurrency { get; set; } = default!;
    public string toCurrency { get; set; } = default!;
    public decimal inputAmount { get; set; }
    public decimal rate { get; set; }
    public decimal convertedAmount { get; set; }

    // Exact timestamp generated by backend server for audit reconstruction (sub-second)
    public DateTimeOffset backendExecutionTimestampUtc { get; set; }

    // Date marker returned by the external provider (e.g., Frankfurter "date")
    public string? providerDate { get; set; }
}
